name: Build addons

on:
    push:
        branches:
            - master
            - scrummer-gh-actions # todo @scrummer: remove this later

jobs:
    build:
        runs-on: ubuntu-latest
#        if: github.event_name == 'push'
        steps:
            - name: Install necessary packages
              run: sudo apt-get update -q && sudo apt-get -y install git vim curl openssh-client openssh-server && sudo apt-get autoclean && sudo rm -rf /var/lib/apt/lists/*

            - name: Test step
              run: echo 'Testing GH Actions'
