name: Build addons

on:
    push:
        branches:
            - master
            - scrummer-gh-actions # todo @scrummer: remove this later

jobs:
    build:
        runs-on: ubuntu-latest
#        if: github.event_name == 'push'
        steps:
            - name: Install necessary packages
              run: apt-get update -q && apt-get -y install sudo git vim curl openssh-client openssh-server && apt-get autoclean && rm -rf /var/lib/apt/lists/*

            - name: Test step
              run: echo 'Testing GH Actions'
